version: '3.8'

services:
  # Wikipedia Agent with Ollama (local inference)
  wikipedia-agent-ollama:
    build: .
    container_name: wikipedia-agent-ollama
    environment:
      - USE_OLLAMA=true
      - OLLAMA_MODEL=qwen3:0.6b
      - OLLAMA_BASE_URL=http://localhost:11434
    ports:
      - "11434:11434"  # Expose Ollama API
    volumes:
      - ollama-data:/home/app/.ollama  # Persist Ollama models
    profiles:
      - ollama
    command: ["--help"]  # Show help by default

  # Wikipedia Agent with cloud providers (API keys required)
  wikipedia-agent-cloud:
    build: .
    container_name: wikipedia-agent-cloud
    environment:
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      
      # Google Gemini Configuration
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-1.5-flash}
      
      # Azure OpenAI Configuration
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-02-15-preview}
      - AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL:-gpt-35-turbo}
      
      # Hugging Face Configuration
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-}
      - HUGGINGFACE_MODEL=${HUGGINGFACE_MODEL:-microsoft/DialoGPT-medium}
    profiles:
      - cloud
    command: ["--help"]  # Show help by default

  # Development environment with all dependencies
  wikipedia-agent-dev:
    build: .
    container_name: wikipedia-agent-dev
    environment:
      # Enable all providers for development
      - USE_OLLAMA=true
      - OLLAMA_MODEL=qwen3:0.6b
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY:-}
    ports:
      - "11434:11434"  # Ollama API
    volumes:
      - ollama-data:/home/app/.ollama
      - .:/home/app  # Mount source code for development
    profiles:
      - dev
    command: ["bash"]  # Interactive shell for development

volumes:
  ollama-data:
    driver: local